import type { Metadata } from "next";
import "./globals.css";
import { ThemeProvider } from "next-themes";
import { BookingProvider } from "@/contexts/BookingContext";
import { Toaster } from "@/components/ui/sonner";
import { AuthProvider } from "@/api/auth/AuthContext";
import ClientLayoutWrapper from "../components/admin/ClientLayoutWrapper";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" suppressHydrationWarning>
            <head />
            <body className="flex flex-col">
                <Toaster
                    position="top-right"
                    expand={true}
                    toastOptions={{
                        classNames: {
                            success: "bg-green-50 border border-green-200 text-green-600 dark:bg-green-900/30 dark:border-green-800 dark:text-green-200",
                            error: "bg-red-50 border border-red-200 text-red-600 dark:bg-red-900/30 dark:border-red-800 dark:text-red-200",
                            info: "bg-blue-50 border border-blue-200 text-blue-600 dark:bg-blue-900/30 dark:border-blue-800 dark:text-blue-200",
                            warning: "bg-yellow-50 border border-yellow-200 text-yellow-600 dark:bg-yellow-900/30 dark:border-yellow-800 dark:text-yellow-200",
                        }
                    }}
                />
                <ThemeProvider
                    attribute="class"
                    defaultTheme="system"
                    enableSystem
                    disableTransitionOnChange
                >
                    <AuthProvider>
                        <BookingProvider>
                            <ClientLayoutWrapper>{children}</ClientLayoutWrapper>
                        </BookingProvider>
                    </AuthProvider>
                </ThemeProvider>
            </body>
        </html>
    );
}
